version: "3.9"

# ATENÇÃO: Essa imagem ao rodar docker-compose up vai levar uns 10min para que o serviço do Laravel inicie
services:
  web:
    image: bitnami/laravel
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
